package com.tytao.community.model;

public class Thumb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb.id
     *
     * @mbg.generated Fri Feb 05 21:29:33 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb.parentId
     *
     * @mbg.generated Fri Feb 05 21:29:33 CST 2021
     */
    private Long parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb.creator
     *
     * @mbg.generated Fri Feb 05 21:29:33 CST 2021
     */
    private Long creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb.id
     *
     * @return the value of thumb.id
     *
     * @mbg.generated Fri Feb 05 21:29:33 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb.id
     *
     * @param id the value for thumb.id
     *
     * @mbg.generated Fri Feb 05 21:29:33 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb.parentId
     *
     * @return the value of thumb.parentId
     *
     * @mbg.generated Fri Feb 05 21:29:33 CST 2021
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb.parentId
     *
     * @param parentid the value for thumb.parentId
     *
     * @mbg.generated Fri Feb 05 21:29:33 CST 2021
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb.creator
     *
     * @return the value of thumb.creator
     *
     * @mbg.generated Fri Feb 05 21:29:33 CST 2021
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb.creator
     *
     * @param creator the value for thumb.creator
     *
     * @mbg.generated Fri Feb 05 21:29:33 CST 2021
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb
     *
     * @mbg.generated Fri Feb 05 21:29:33 CST 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Thumb other = (Thumb) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getParentid() == null ? other.getParentid() == null : this.getParentid().equals(other.getParentid()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb
     *
     * @mbg.generated Fri Feb 05 21:29:33 CST 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getParentid() == null) ? 0 : getParentid().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        return result;
    }
}